= Connecting, are we too connected?
LightGuardjp
2013-02-18

I finished watching _Connecting_ today and it's stirred some thoughts.
My first inclination of course was to tweet about it, but I quickly decided that wouldn't work well, not enough space.
Here I am writing a blog post about it instead. You can see the video below if you haven't seen it yet:

++++
<iframe src="http://player.vimeo.com/video/52861634?title=0&amp;byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> <p><a href="http://vimeo.com/52861634">Connecting (Full Film)</a> from <a href="http://vimeo.com/user1384354">Bassett &amp; Partners</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
++++

== Are we going too far?

This is my main idea here. While I love how things are becoming more and more connected (yes, that's the technologist speaking), I'm also very worried about it.
I remember growing up (which honestly wasn't that long ago) you had to either call, personally visit, or send something to their house to connect with someone.
That's right, a land line phone, letter, or in person communication was it. If they weren't there you you left some sort of message or note and hoped for the best.
Sure you wished there was a better way to get in contact with people, but you made it work. Fast forward to the future where the majority of us have at least two ways of near instant communication (well, in the developed world at least): cellphone and some other electronic means (email, IM, twitter, facebook, etc.).
This is great if you want to get a hold of someone or stay "connected." The other part of me is wondering if the lack of connectivity was a good thing.
I constantly wake up to nearly a 100 emails between work and personal email every day (not counting spam), multiple status updates on G+, Twitter, Facebook if I choose to visit them and a mountain of blogs and other "news" to read should I so choose. I know there are others out there with far more.
To me that just screams information overload, and if we continue to add more connections it will only get worse.
Sure you can talk about making it natural and what not, but the fact remains it's still information that you will have to process, and most of us don't process information quickly.
How many of us feel stressed more often than not? I think all of this information and feeling like you have to stay "connected" and "caught up" all the time is a big part of it.

== Is less more in this context?

I really do wonder if dialing all of this back would be better. Would it be better if all I really had to worry about was myself, my family, and survival for the next few months? 
Go outside and guess what the weather was going to be like for the day. Enjoy the breeze while sitting on my porch with my family.
Not worrying about what was happening on the other side of global and how that would affect me later, or what's happening at a national level and guessing how that will change my life.
I'm sure most of us that go on vacation and end up leaving the electronics either at home or off the whole time find it very refreshing not having to worry about all of that stuff for the duration of things.
If that's the case for a one or two week vacation, would it not hold true more long term?
 
