= Slight Introspection
LightGuardjp 
2013-07-21

I had a very enjoyable day at Church today. 
The last meeting, Elders Quorum, was particularly enjoyable.
For those not familiar with the LDS religion, or Mormon religion, for one of the three hours of church meetings we have on Sunday the men and the women separate to go to their own classes, Elders (or High Priests depending on age and calling) for the men and Relief Society for the women.
Sometimes the lessons are similar or from the same manual, but often times they are not.

We believe our boys are going through another round of Croup, and my second daughter wanted to stay home with Mommy.
Can't say I agree with her sentiments, but that's not part of today's entry.
My wife stayed home with the other three and I took our oldest with me to attend church.
The first too hours were good, but nothing overly special.
We started with Sacrament Meeting, often called Communion in other religions, then have Sunday School.
This week's lesson came from one of our manuals from a series of books taken from sermons, biographies and other conference addresses from our past prophets.
This year we're learning about http://www.lds.org/churchhistory/presidents/controllers/potcController.jsp?topic=facts&leader=5[President Lorenzo Snow].

The chapter for the week was about trusting the Lord, or at least that's where the discussion went.
Many of us had thoughts to share or other comments during the lesson, but the experiences some of the other men shared that really made me think.
I believe it was also those experiences that helped bring the Spirit into the meeting too.
I thought during that class that all these people have had wonderful experiences where they have helped others, or had instances where the Lord has helped them solve problems, but I couldn't really think of anything major in my life.
It certainly could be that I couldn't think of anything, or maybe I really haven't had any of those experiences.
If that's the case, it makes me quite sad.
Just like everyone, I have my own pet sins I easily fall prey to.
Part of me wonders if those are things keeping me from having those great experiences, or if I'm simply not remembering them.

I'd love to hear further comments from you in the comment section. Like the rest of this blog, I hope to write more frequently, but it seems as though it's like keeping a journal: I don't write as often as I should.
